name: Waka Readme

on:
  schedule:
    # Runs at 12am IST (adjusted to UTC time)
    - cron: '30 18 * * *'
  workflow_dispatch:  # Allows manual execution from the GitHub Actions tab

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
